baseURL = "https://boyan-soubachov.github.io/"
languageCode = "en-us"
title = "The 🐻 code"
theme = "smol"
publishdir = "../"
[params]
    subtitle = "Just me, my opinions and an audience"
    dateFmt = "02.01.2006 15:04"
[menu]
#   [[menu.main]]
#         identifier = "posts"
#         name = "Posts"
#         url = "/posts/"
#         weight = 1 

#   [[menu.main]]
#         identifier = "categories"
#         name = "Categories"
#         url = "/categories/"
#         weight = 2 

# Footer
  [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/boyan-soubachov"
        weight = 1 

    [[menu.footer]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/bsoubachov/"
        weight = 2
